/**
 * حَرِّك | HARRIK — Worker entrypoint (fetch + scheduled).
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * Two features were fully built but never ran on their own:
 *
 *   - `POST /api/alerts/escalate` — escalates a parking alert that nobody has
 *     acknowledged, so the security team is notified when the owner cannot be
 *     reached. Without a scheduler it only ran *lazily*, when someone happened
 *     to open the alerts screen or the dashboard. If nobody opened the app the
 *     escalation never happened — which is exactly the situation it exists for.
 *   - `POST /api/reports/email` — the scheduled operations report. Its own
 *     docblock says "Cloudflare Worker scheduled handler"; there was none.
 *
 * Cloudflare invokes Cron Triggers through a worker's `scheduled()` export, and
 * the worker that `@opennextjs/cloudflare` generates (`.open-next/worker.js`)
 * exports only `fetch`. That file is regenerated by every build, so it cannot
 * be edited. This module wraps it instead: `fetch` is passed straight through
 * and `scheduled` is added on top. `wrangler.jsonc` points `main` here.
 *
 * The job routing itself lives in ./cron-jobs.mjs so it can be unit-tested
 * without a Cloudflare build.
 *
 * Required secret: `CRON_SECRET` (`npx wrangler secret put CRON_SECRET`).
 * Without it both jobs are skipped with a log line instead of failing.
 */

// The generated OpenNext worker. Resolved by wrangler at bundle time; it does
// not exist until `opennextjs-cloudflare build` has run.
import openNextWorker from "../.open-next/worker.js";
import { runScheduledJob } from "./cron-jobs.mjs";

// Durable Object classes must stay exported from the worker entrypoint, or a
// binding that references them cannot resolve. They are re-exported verbatim.
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "../.open-next/worker.js";

export default {
  fetch: (request, env, ctx) => openNextWorker.fetch(request, env, ctx),

  /** Cron entrypoint — `event.cron` says which schedule fired. */
  async scheduled(event, env, ctx) {
    await runScheduledJob({
      cron: event.cron,
      env,
      ctx,
      fetchHandler: (request, e, c) => openNextWorker.fetch(request, e, c),
    });
  },
};
